version: 2.1

jobs:
  build:
    working_directory: ~/mycode
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: pushd ~/mycode/www/; python3 -m http.server 8000 & exit
  test:
    working_directory: ~/mycode
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: pushd ~/mycode/www/; python3 -m http.server 8000 &
      - run: sh click-test.sh
  deploy:
    working_directory: ~/mycode
    machine:
        image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install elastic bean CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: aws s3 sync ~/mycode/www s3://cci-myapp

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
