version: 2.1

jobs:
  mybuildjob:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: pushd ~/circleci-python/www/; python3 -m http.server 8000 & exit
  mytestjob:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: sh click-test.sh

workflows:
  build_and_test:
    jobs:
      - mybuildjob
      - mytestjob:
          requires:
            - mybuildjob
