version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  build:
    working_directory: ~/mycode
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: pushd ~/mycode/www/; python3 -m http.server 8000 & exit
  test:
    working_directory: ~/mycode
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: pushd ~/mycode/www/; python3 -m http.server 8000 &
      - run: sh click-test.sh
  deploy:
    working_directory: ~/mycode
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: copy code to s3 -- AWS Bean Stalk deploys from here
          command: aws s3 sync ~/mycode/www s3://cci-myapp

workflows:
  mypipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
