version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: cd ~/circleci-python/www
      - run: ls
      - run: python3 -m http.server 8000
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: echo "hello"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
